[package]
name = "turbo"
version = "5.2.4"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
ignore = "0.4.23"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
xxhash-rust = { version = "0.8.12", features = ["xxh3"] }

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "indexer"
harness = false
