name: Pest Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "**.php"
      - "composer.lock"
  pull_request:
    paths:
      - "**.php"
      - "composer.lock"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Wait for Redis (TCP)
        run: |
          for i in {1..10}; do
            nc -z 127.0.0.1 6379 && echo "Redis ready" && break
            echo "Waiting for Redis..."
            sleep 1
          done

      - name: Install
        run: composer kirby

      - name: Test code
        run: vendor/bin/pest --ci
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
